### PR TITLE
Add bare metal performance tests for Culsans

### PR DESCRIPTION
**Pull request by ricted98**

### CODE REVIEW

**Comment by luca-valente** [comment]
Looks good! Maybe add some details to the README.

**Comment by ricted98** [comment]
Thanks. An improved README was added. Let me know if you have additional suggestions!

**Comment by luca-valente** [comment]
It's ready for merging imo :smile:

**Comment by mattsini1** [comment]
Perfect, thank you guys!!

**Review by mattsini1 — APPROVED** [review]
Let's merge it!

**Pull request merged**
